In [1]:
import numpy as np
import pprint 

In [2]:
# adj = np.array()
# l1=input("Enter the number of websites")
l1=3

In [3]:
# for i in range(l1):
#     for j in range(l1):
#         adj[i][j] = input("Enter link of node")
#taking in adjacency matrix        

In [4]:
adj=np.array([[1,1,1],[1,0,1],[0,1,0]])

In [5]:
# adj.reshape(l1,l1)

In [6]:
atr=np.transpose(adj)
hubm=np.transpose(np.ones(3))#initially all hub weights are 1

In [7]:
pp=pprint.PrettyPrinter(indent=4)

In [8]:
authm=np.matmul(atr,hubm)
pp.pprint(authm)

array([2., 2., 2.])


In [9]:
norm=np.sum(authm)
#normalising..
authm=np.true_divide(authm,norm)

In [10]:
#after dividing 
pp.pprint(authm)

array([0.33333333, 0.33333333, 0.33333333])


In [11]:
hubm=np.matmul(adj,authm)
pp.pprint(hubm)

array([1.        , 0.66666667, 0.33333333])


In [12]:
#above first iteration has been completed

In [13]:
#lets say we have to perform 3 more iterations..
iter_num=3

In [14]:
for i in range(iter_num):
    authm=np.matmul(atr,hubm)
    norm=np.sum(authm)
    authm=np.true_divide(authm,norm)
    hubm=np.matmul(adj,authm)

In [15]:
pp.pprint(authm)

array([0.36538462, 0.26923077, 0.36538462])


In [17]:
pp.pprint(hubm)

array([1.        , 0.73076923, 0.26923077])
